/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 *by 'ricalo' at '2/26/17 12:30 AM' with Gradle 2.10
 *
 * @author ricalo, @date 2/26/17 12:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
